on:
  # This is triggered from a dispatch by the openeyes/openeyes repo
  repository_dispatch:
    types: [pull_request, pull_request_syncronize, pull_request_reopened]
  workflow_dispatch:

env:
  # This is the name of the branch that triggered the workflow
  BRANCH: ${{ github.event.client_payload.branch }}
  GITHUB_REF_NAME: ${{ github.event.client_payload.message.GITHUB_REF_NAME }}
  GITHUB_REF: ${{ github.event.client_payload.message.GITHUB_REF }}
  GITHUB_HEAD_REF: ${{ github.event.client_payload.message.GITHUB_HEAD_REF }}
  GITHUB_BASE_REF: ${{ github.event.client_payload.message.GITHUB_BASE_REF }}
  GITHUB_HEAD_SHA: ${{ github.event.client_payload.message.GITHUB_HEAD_SHA }}
  GITHUB_BASE_SHA: ${{ github.event.client_payload.message.GITHUB_BASE_SHA }}
  GITHUB_PULL_REQUEST: ${{ github.event.client_payload.message.GITHUB_PULL_REQUEST }}
  GITHUB_REPOSITORY: ${{ github.event.client_payload.message.GITHUB_REPOSITORY }}
  GITHUB_RUN_ID: ${{ github.event.client_payload.message.GITHUB_RUN_ID }}
  GITHUB_RUN_NUMBER: ${{ github.event.client_payload.message.GITHUB_RUN_NUMBER }}
  GITHUB_RUN_ATTEMPT: ${{ github.event.client_payload.message.GITHUB_RUN_ATTEMPT }}


jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'currents.dev' }}
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v3
        # populate commit message for merge commits
        # see https://currents.dev/readme/ci-setup/github-actions
        with:
          ref: ${{ env.GITHUB_HEAD_SHA }}

      - name: Resolve ref
        uses: rlespinasse/github-slug-action@v3.x

      - name: Run docker
        run: |
          TESTS_TO_RUN=CURRENTS_CLOUD_SHORT CURRENTS_RECORD_KEY=${{ secrets.CURRENTS_RECORD_KEY }} PUID=$(id -u) SSH_PRIVATE_KEY='${{ secrets.TKL_DEPLOY_PRIVATE_KEY }}' BUILD_BRANCH=${{ env.GITHUB_REF }} BUILD_ID=${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}} docker compose -f protected/tests/docker-compose.yml run --use-aliases web
        run: |
          TESTS_TO_RUN=CURRENTS_CLOUD_SHORT
          CURRENTS_RECORD_KEY=${{ secrets.CURRENTS_RECORD_KEY }}
          PUID=$(id -u)
          SSH_PRIVATE_KEY='${{ secrets.TKL_DEPLOY_PRIVATE_KEY }}'
          BUILD_BRANCH=${{ env.GITHUB_HEAD_REF }}
          BUILD_ID=${{ env.GITHUB_REPOSITORY }}-${{ github.run_id }}-${{ github.run_attempt}}
          docker compose -f protected/tests/docker-compose.yml run --use-aliases web

      - name: Cancel the run if workflow is cancelled
        if: ${{ cancelled() }}
        uses: currents-dev/cancel-run-gh-action@v1
        with:
          api-token: ${{ secrets.CURRENTS_API_KEY }}
          github-run-id: ${{ github.run_id }}
          github-run-attempt: ${{ github.run_attempt }}