name: Cypress runner

on:
  # This is triggered from a dispatch by the openeyes/openeyes repo
  repository_dispatch:
    types: [pull_request, pull_request_syncronize, pull_request_reopened]

env:
  GITHUB_REF_NAME: ${{ github.event.client_payload.GITHUB_REF_NAME }}
  GITHUB_REF: ${{ github.event.client_payload.GITHUB_REF }}
  GITHUB_HEAD_REF: ${{ github.event.client_payload.GITHUB_HEAD_REF }}
  GITHUB_BASE_REF: ${{ github.event.client_payload.GITHUB_BASE_REF }}
  GITHUB_HEAD_SHA: ${{ github.event.client_payload.GITHUB_HEAD_SHA }}
  GITHUB_BASE_SHA: ${{ github.event.client_payload.GITHUB_BASE_SHA }}
  GITHUB_PULL_REQUEST: ${{ github.event.client_payload.GITHUB_PULL_REQUEST }}
  GITHUB_REPOSITORY: ${{ github.event.client_payload.GITHUB_REPOSITORY }}
  GITHUB_RUN_ID: ${{ github.event.client_payload.GITHUB_RUN_ID }}
  GITHUB_RUN_NUMBER: ${{ github.event.client_payload.GITHUB_RUN_NUMBER }}
  GITHUB_RUN_ATTEMPT: ${{ github.event.client_payload.GITHUB_RUN_ATTEMPT }}

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    name: Cypress runner ${{ github.event.client_payload.GITHUB_REF_NAME }}
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4
        # populate commit message for merge commits
        # see https://currents.dev/readme/ci-setup/github-actions
        with:
          repository: openeyes/openeyes
          ssh-key: ${{ secrets.TKL_DEPLOY_PRIVATE_KEY }}
          ref: ${{ env.GITHUB_HEAD_SHA }}

      # - name: Resolve ref
      #   uses: rlespinasse/github-slug-action@v3.x

      # write environment variables to a docker compose .env file
      - name: Write variables to compose .envfile
        run: |
          echo "CURRENTS_RECORD_KEY=${{ secrets.CURRENTS_RECORD_KEY }}" >> protected/tests/.env
          echo "TESTS_TO_RUN=CURRENTS_CLOUD_SHORT" >> protected/tests/.env
          echo "PUID=$(id -u)" >> protected/tests/.env
          echo "SSH_PRIVATE_KEY='${{ secrets.TKL_DEPLOY_PRIVATE_KEY }}'" >> protected/tests/.env
          echo "BUILD_BRANCH=${{ env.GITHUB_HEAD_REF }}" >> protected/tests/.env
          echo "BUILD_ID=${{ env.GITHUB_REPOSITORY }}-${{ env.GITHUB_RUN_ID }}-${{ env.GITHUB_RUN_ATTEMPT}}" >> protected/tests/.env


      - name: Run docker
        run: |
          TESTS_TO_RUN=CURRENTS_CLOUD_SHORT \
          CURRENTS_RECORD_KEY=${{ secrets.CURRENTS_RECORD_KEY }} \
          PUID=$(id -u) \
          SSH_PRIVATE_KEY='${{ secrets.TKL_DEPLOY_PRIVATE_KEY }}' \
          BUILD_BRANCH=${{ env.GITHUB_HEAD_REF }} \
          BUILD_ID=${{ env.GITHUB_REPOSITORY }}-${{ env.GITHUB_RUN_ID }}-${{ env.GITHUB_RUN_ATTEMPT}} \
          docker compose -f protected/tests/docker-compose.yml --env-file protected/tests/.env run --use-aliases web

      - name: Cancel the run if workflow is cancelled
        if: ${{ cancelled() }}
        uses: currents-dev/cancel-run-gh-action@v1
        with:
          api-token: ${{ secrets.CURRENTS_API_KEY }}
          github-run-id: ${{ github.run_id }}
          github-run-attempt: ${{ github.run_attempt }}