name: PHPUnit branch runner

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: true

env:
  GITHUB_HEAD_REF: ${{ github.event.inputs.branch }}
  GITHUB_REPOSITORY: openeyes/openeyes
  GITHUB_RUN_ID: ${{ github.run_id }}
  GITHUB_RUN_NUMBER: ${{ github.run_number }}
  GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # run 3 copies of the current job in parallel
        test-type: [PHPUNIT-SAMPLE , PHPUNIT-FIXTURES]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Checkout
        uses: actions/checkout@v4
        # populate commit message for merge commits
        # see https://currents.dev/readme/ci-setup/github-actions
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ssh-key: ${{ secrets.TKL_DEPLOY_PRIVATE_KEY }}
          ref: ${{ env.GITHUB_HEAD_REF }}

      # write environment variables to a docker compose .env file
      - name: Write variables to compose .envfile
        run: |
          echo "TESTS_TO_RUN=${{ matrix.test-type }}" >> protected/tests/.env
          echo "PUID=$(id -u)" >> protected/tests/.env
          echo "SSH_PRIVATE_KEY='${{ secrets.TKL_DEPLOY_PRIVATE_KEY }}'" >> protected/tests/.env
          echo "BUILD_BRANCH=${{ env.GITHUB_HEAD_REF }}" >> protected/tests/.env
          echo "BUILD_ID=${{ env.GITHUB_REPOSITORY }}-${{ env.GITHUB_RUN_ID }}-${{ env.GITHUB_RUN_ATTEMPT}}" >> protected/tests/.env

      - name: Run docker
        run: |
          docker compose -f protected/tests/docker-compose.yml --env-file protected/tests/.env run --use-aliases web
